#!/usr/bin/env bash

bspc config border_width                      0
bspc config window_gap                        20
bspc config top_padding                       30
bspc config bottom_padding                    30
bspc config left_padding                      0
bspc config right_padding                     0

bspc config remove_disabled_monitors          true
bspc config remove_unplugged_monitors         true

bspc config split_ratio                       0.52
bspc config borderless_monocle                true
bspc config gapless_monocle                   true
bspc config focus_follows_pointer             true

bspc config pointer_modifier                  mod4
bspc config pointer_action1                   move
bspc config pointer_action2                   resize_side
bspc config pointer_action3                   resize_corner

bspc config external_rules_command            "$HOME/.config/bspwm/bspwm-rules"

# Configure multiple monitors

monitors=( $( bspc query -M --names  ) )

min=1
mon=1

for monitor in ${monitors[@]} ; do
  div=$(( 10 / ${#monitors[@]} ))
  bspc monitor ${monitor} -n ${monitor} -d $(seq -f "workspace/%g" $min $(($div*$mon)))
  min=$(( $min + $div ))
  let mon++
done
