#!/usr/bin/env bash
# deps: jq, bspwm

LINESIZE=20
GAPSIZE=8

function _monitSize
{
	if [ -z $1 ]; then MONITORS=$(bspc query -M); else MONITORS=$1; fi
	for MONITOR in ${MONITORS}; do
		VALUES=$(bspc query -m $MONITOR -T | jq .rectangle)
		X=$(echo $VALUES | jq .x)
		Y=$(echo $VALUES | jq .y)
		WIDTH=$(echo $VALUES | jq .width)
		HEIGHT=$(echo $VALUES | jq .height)

		WIDTH=$(echo "${WIDTH}-(${GAPSIZE}*2)" | bc)
		HEIGHT=${LINESIZE}

		if [ ${X} -gt 0 ] ; then
			X=$(echo "${X}+(${GAPSIZE})" | bc)
			Y=$(echo "${Y}+${GAPSIZE}" | bc )
		else
			X=$(echo "${X}+${GAPSIZE}" | bc )
			Y=$(echo "${Y}+${GAPSIZE}" | bc )
		fi

		echo ${WIDTH}x${HEIGHT}+${X}+${Y}

	done
}

