#!/usr/bin/env bash
# 

pkill polybar

M_OFFSET=40

for MONITOR in $( xrandr --query | sed 's/primary //g' | awk -F '[ x+]' '/\<connected\>/{print $1":"$3":"$4}' ) ; do
	export M_NAME=$(echo ${MONITOR} | cut -d ':' -f 1 ) 
	export M_OFF_X=20
	export M_OFF_Y=20
	export M_HEIGHT=20
	export M_WIDTH=$(echo $( echo ${MONITOR} | cut -d ':' -f 2 ) - ${M_OFFSET} | bc )
  if [ -f ~/.config/polybar/.env ]  ; then
    source ~/.config/polybar/.env
  fi
	polybar -r -q top &
done
