#!/bin/sh

. $HOME/.bin/colr
song=$(mpc playlist | dmenu -nb "#$bg" -nf "#$fg" -sb "#$cyn" -sf "#$blk" -l 30 -w 320 -fn "lemon-8" -p "Search >" -x 0 -y 25)

IFS='
'

i=0
mpc playlist | while IFS= read -r line ; do
	if [[ $line = $song ]]; then
		mpc play $((i + 1))
	fi		
	i=$((i + 1))
done
