#!/usr/bin/python

import subprocess, datetime
workspaces = subprocess.getoutput('bspc query -D').split('\n')
current = subprocess.getoutput('bspc query -D -d')
line = ""
for workspace in workspaces:
	if workspace == current:
		line += "%{F#385853}" + workspace + "%{F-}"
	else:
		line += '%{A:bspc desktop -f ' + workspace + ':}'+ workspace + '%{A}'
	line += ' | '
print(line)
