#!/usr/bin/python
import sys
last = ""
for line in sys.stdin:
	if line == last or line == "":
		sys.exit()
	else:
		last = line
		line = line.split(':')
		out = ""
		for i in range(1, 8):
			workspace = line[i][1:]
			out += '%{A:bspc desktop -f ' + workspace + ':} '
			if line[i].startswith('O') or line[i].startswith('F'): #Focused
				out += '\uf111'
			elif line[i].startswith('o'):
				out += '\uf192'
			elif line[i].startswith('f'):
				out += '\uf1db'
			out += ' %{A}'
	print('%W' + out)
